[package]
name = "solana_faucet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-client = "1.8.10"
solana-sdk = "1.8.10"
tokio = { version = "1.0", features = ["full"] }
shellexpand = "2.0"